# Generated by Django 4.2.7 on 2025-04-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('audi', 'H.M. AUDITORIUM'), ('soorty', 'SOORTY'), ('tariq_rafi', 'TARIQ RAFI')], default='audi', max_length=200),
        ),
    ]
