# Generated by Django 4.2.7 on 2025-04-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sale_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='sale_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='sale_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='sale_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_type',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=10),
        ),
    ]
