# Generated by Django 4.2.7 on 2025-04-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_sale_end_date_event_sale_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='sale_end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sale_start_time',
        ),
    ]
