# Generated by Django 4.2.7 on 2025-04-11 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_sale_end_date_event_sale_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='sale_end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sale_start_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ticket_price',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ticket_type',
        ),
    ]
